# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.IntegerField(choices=[(1, b'percentage'), (2, b'value')])),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, b'Montag'), (1, b'Dienstag'), (2, b'Mittwoch'), (3, b'Donnerstag'), (4, b'Freitag'), (5, b'Samstag'), (6, b'Sonntag')])),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('items', models.ManyToManyField(to='hotpot.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemRetailerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_year', models.DateField(default=datetime.date.today)),
                ('order_number', models.IntegerField(unique_for_year=models.DateField(default=datetime.date.today))),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('note', models.TextField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.MenuItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('treshold', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
            ],
            options={
                'verbose_name': 'Shipping',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotpot.Retailer'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('order_year', 'order_number')]),
        ),
        migrations.AddField(
            model_name='menuitemretailerprice',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.Retailer'),
        ),
        migrations.AddField(
            model_name='deliverydays',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.Shipping'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.Order'),
        ),
    ]
