# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from random import randint

class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0002_auto_20160220_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.AutoField(default=randint(0,9), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
