# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0002_auto_20160226_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='order',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
