# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0003_auto_20160226_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=2047),
        ),
    ]
