# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0004_auto_20160226_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.MenuItem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.Menu')),
            ],
        ),
    ]
