# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0004_auto_20160221_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(max_length=2047),
        ),
    ]
