# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0005_itembatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembatch',
            name='menu',
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='hotpot.ItemBatch'),
        ),
    ]
