# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0006_auto_20160227_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='itembatch',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotpot.Menu'),
            preserve_default=False,
        ),
    ]
