# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0006_auto_20160223_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotpot.Retailer'),
        ),
    ]
