# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0007_orderitem_retailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemRetailerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.MenuItem')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.Retailer')),
            ],
        ),
    ]
