# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0007_auto_20160227_1018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itembatch',
            unique_together=set([('item', 'menu')]),
        ),
    ]
