# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0009_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='treshold',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
