# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotpot', '0010_auto_20160223_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, b'Montag'), (1, b'Dienstag'), (2, b'Mittwoch'), (3, b'Donnerstag'), (4, b'Freitag'), (5, b'Samstag'), (6, b'Sonntag')])),
                ('time', models.TimeField()),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotpot.Shipping')),
            ],
        ),
    ]
